name: Deploy Terraform

on:
  push:
    branches:
      - main  # Mude para o nome do branch principal do seu repositório

jobs:
  deploy:
    name: Deploy Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Mude para a versão do Terraform que você está usando

      - name: Terraform Init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -var="access_key=$AWS_ACCESS_KEY_ID" -var="secret_key=$AWS_SECRET_ACCESS_KEY" -var="vpc_id=$AWS_VPC_ID" -var="subnet=$AWS_SUBNET" -var="role_action_aws=$ARN_ROLE" -var-file=./environments/hom/stage.tfvars

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
